# Declarative group & permission config for UniHanko

groups:
  "feature:import":
    inherits: []
    models: {}
    custom_perms: {}
  
  "feature:export":
    inherits: []
    models: {}
    custom_perms: {}
  
  "foundation:helppages:viewer":
    inherits: []
    models:
      helppages.HelpPage: [view]
    custom_perms: {}

  "foundation:annotations:commenter":
    inherits: []
    models:
      annotations.Annotation: [view, add, change, delete]
    custom_perms: {}

  "foundation:personnel:viewer":  # ← Renamed from module:personnel:viewer
    inherits: []
    models:
      people.Person: [view]
      people.PersonRole: [view]
      people.Role: [view]
      people.RoleTransitionReason: [view]
    custom_perms: {}

  "feature:basics":  # ← Bundle all foundation groups
    inherits:
      - "foundation:helppages:viewer"
      - "foundation:annotations:commenter"
      - "foundation:personnel:viewer"
    models: {}
    custom_perms: {}

  "module:employees:editor":
    inherits:
      - "feature:basics"
    models:
      employees.Employee: [view]
      employees.HolidayCalendar: [view]
      employees.EmploymentDocument: [view, add, change, delete]
      employees.TimeSheet: [view, add, change]
      employees.TimeEntry: [view, add, change, delete]
      employees.EmployeeLeaveYear: [view]
    custom_perms: {}

  "module:employees:manager":
    inherits:
      - "module:employees:editor"
    models:
      employees.Employee: [add, change]
      employees.HolidayCalendar: [add, change]
      employees.EmployeeLeaveYear: [change]
    custom_perms: {}

  "module:organisation:editor":
    inherits:
      - "feature:basics"
    models:
      organisation.OrgInfo: [view]
    custom_perms: {}
  
  "module:organisation:manager":
    inherits:
      - "module:organisation:editor"
    models:
      organisation.OrgInfo: [change]
    custom_perms: {}

  "module:personnel:editor":
    inherits:
      - "feature:basics"
    models:
      people.Person:             [add, change]
      people.PersonRole:         [add, change]
    custom_perms: {}                            

  "module:personnel:manager":
    inherits:
      - "module:personnel:editor"
    models:
      people.Role:               [add, change]
      people.RoleTransitionReason: [add, change]
    custom_perms: {}
  
  "module:finances:editor":
    inherits:
      - "feature:basics"
    models:
      finances.FiscalYear:       [view]
      finances.PaymentPlan:      [view, add, change]
    custom_perms: {}

  "module:finances:manager":
    inherits:
      - "module:finances:editor"
    models:
      finances.PaymentPlan: [delete]
    custom_perms: {} 

  "module:hankosign:editor":
    inherits:
      - "feature:basics"
    models:
      hankosign.Action: [view]
      hankosign.Policy: [view]
      hankosign.Signatory: [view]
      hankosign.Signature: [view]
    custom_perms: {}

  "module:hankosign:manager":
    inherits:
      - "module:hankosign:editor"
    models:
      hankosign.Action: [add, change]
      hankosign.Policy: [add, change]
      hankosign.Signatory: [add, change]
      hankosign.Signature: [add, change]
    custom_perms: {}

  "module:helppages:editor":
    inherits:
      - "feature:basics"
    models:
      helppages.HelpPage: [view]
    custom_perms: {}

  "module:helppages:manager":
    inherits:
      - "module:helppages:editor"
    models:
      helppages.HelpPage: [change]
  custom_perms: {}

  "module:assembly:editor":
    inherits:
      - "feature:basics"
    models:
      assembly.Term: [view]
      assembly.Composition: [view]
      assembly.Mandate: [view]
      assembly.Session: [view, add, change]
      assembly.SessionItem: [view, add, change, delete]
      assembly.Vote: [view, add, change]
    custom_perms: {}

  "module:assembly:manager":
    inherits:
      - "module:assembly:editor"
    models:
      assembly.Term: [add, change]
      assembly.Composition: [add, change]
      assembly.Mandate: [add, change]
    custom_perms: {}

  "module:academia:editor":
    inherits:
      - "feature:basics"
    models:
      academia.Semester: [view]
      academia.InboxRequest: [view, add, change]
      academia.InboxCourse: [view, add, change, delete]
    custom_perms: {}

  "module:academia:manager":
    inherits:
      - "module:academia:editor"
    models:
      academia.Semester: [add, change]
    custom_perms: {}

  "module:academia_audit:editor":
    inherits:
      - "feature:basics"
    models:
      academia_audit.AuditSemester: [view]
      academia_audit.AuditEntry: [view]
    custom_perms: {}

  "module:academia_audit:manager":
    inherits:
      - "module:academia_audit:editor"
    models:
      academia_audit.AuditSemester: [add, change]
      academia_audit.AuditEntry: [add, change]
    custom_perms: {}